# Generated by Django 3.2.5 on 2024-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='country',
            field=models.CharField(default='USA', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='country_code',
            field=models.CharField(default='+1', max_length=5),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='state',
            field=models.CharField(default='CA', max_length=50),
        ),
    ]
